-- ----------------------------------------------------------------
--  DATA BASE: COGNITIVE_SERVICE
--  DESCRIPTION: SE ALMACENA TRAZA DE PROCESAMIENTO.
-- ----------------------------------------------------------------

CREATE DATABASE COGNITIVE_SERVICE;
USE COGNITIVE_SERVICE;

CREATE TABLE RECEIVED
(
    UUID      VARCHAR(36) NOT NULL PRIMARY KEY COMMENT 'IDENTIFICADOR UNIVERSAL UNICO DE SOLICITUD',
    CREATE_AT TIMESTAMP   NOT NULL DEFAULT NOW() COMMENT 'FECHA DE CREACIÓN DEL REGISTRO',
    EXTENSION VARCHAR(6)  NOT NULL COMMENT 'EXTENSION DEL DOCUMENTO A PROCESAR'
) ENGINE = InnoDB;

CREATE TABLE DOCUMENT_STORED
(
    UUID       VARCHAR(36)  NOT NULL PRIMARY KEY COMMENT 'IDENTIFICADOR UNIVERSAL UNICO DE SOLICITUD',
    CREATE_AT  DATETIME(0)  NOT NULL DEFAULT NOW() COMMENT 'FECHA DE CREACIÓN DEL REGISTRO',
    OBJECT_KEY VARCHAR(200) NOT NULL COMMENT 'PATH ABSOLUTO DEL OBJETO ALMACENADO EN S3',
    CONSTRAINT STORED_UUID_FK FOREIGN KEY (UUID)
        REFERENCES COGNITIVE_SERVICE.RECEIVED (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT,
    UNIQUE KEY STORED_OBJECT_KEY_UQ (OBJECT_KEY)
) ENGINE = InnoDB;

CREATE TABLE PROCESSED
(
    UUID      VARCHAR(36) NOT NULL PRIMARY KEY COMMENT 'IDENTIFICADOR UNIVERSAL UNICO DE SOLICITUD',
    CREATE_AT TIMESTAMP   NOT NULL DEFAULT NOW() COMMENT 'FECHA DE CREACIÓN DEL REGISTRO',
    TYPE      VARCHAR(36) NOT NULL COMMENT 'TIPO DE PROCESAMIENTO PARA TEXTRACT EN AWS',
    CONSTRAINT PROCESSED_UUID_FK FOREIGN KEY (UUID)
        REFERENCES COGNITIVE_SERVICE.DOCUMENT_STORED (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE = InnoDB;